package kotlinx.coroutines;

import kotlin.C4789l;
import kotlin.p042a0.C9069g;

@C4789l(mo16639bv = {1, 0, 3}, mo16640d1 = {"\u0000\u001e\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0003\n\u0002\b\u0002\bf\u0018\u0000 \b2\u00020\u0001:\u0001\bJ\u0018\u0010\u0002\u001a\u00020\u00032\u0006\u0010\u0004\u001a\u00020\u00052\u0006\u0010\u0006\u001a\u00020\u0007H&Â¨\u0006\t"}, mo16641d2 = {"Lkotlinx/coroutines/CoroutineExceptionHandler;", "Lkotlin/coroutines/CoroutineContext$Element;", "handleException", "", "context", "Lkotlin/coroutines/CoroutineContext;", "exception", "", "Key", "kotlinx-coroutines-core"}, mo16642k = 1, mo16643mv = {1, 1, 16})
/* compiled from: CoroutineExceptionHandler.kt */
public interface CoroutineExceptionHandler extends C9069g.C9072b {

    /* renamed from: d */
    public static final C12173a f31941d = C12173a.f31942a;

    /* renamed from: kotlinx.coroutines.CoroutineExceptionHandler$a */
    /* compiled from: CoroutineExceptionHandler.kt */
    public static final class C12173a implements C9069g.C9074c<CoroutineExceptionHandler> {

        /* renamed from: a */
        static final /* synthetic */ C12173a f31942a = new C12173a();

        private C12173a() {
        }
    }

    void handleException(C9069g gVar, Throwable th);
}
